project_id = "djtnimphritsoxtoeouh"

[functions.lookup-stores]
verify_jwt = false

[functions.apply-referral]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.monthly-recap-ai]
verify_jwt = false

[functions.scan-receipt]
verify_jwt = false

[functions.suggest-alternatives]
verify_jwt = false

[functions.validate-nova-token]
verify_jwt = false

[functions.validate-iap-receipt]
verify_jwt = false

[functions.revenuecat-webhook]
verify_jwt = false
