project_id = "djtnimphritsoxtoeouh"

[functions.lookup-stores]
verify_jwt = false

[functions.apply-referral]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.monthly-recap-ai]
verify_jwt = false

[functions.scan-receipt]
verify_jwt = false

[functions.suggest-alternatives]
verify_jwt = false

[functions.validate-nova-token]
verify_jwt = false

[functions.validate-iap-receipt]
verify_jwt = false

[functions.revenuecat-webhook]
verify_jwt = false

[functions.nearby-stores]
verify_jwt = false

[functions.estimate-grocery-prices]
verify_jwt = false

[functions.sync-novawealth-access]
verify_jwt = false

[functions.handle-standalone-webhook]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.track-nw-referral]
verify_jwt = false

[functions.plaid-create-link-token]
verify_jwt = false

[functions.plaid-exchange-token]
verify_jwt = false

[functions.plaid-sync-balance]
verify_jwt = false

[functions.plaid-link-bank]
verify_jwt = false

[functions.plaid-exchange-bank-token]
verify_jwt = false
